### ISSUE TITLE
Bisa dijelaskan ini dibuat apa?

### ISSUE THREAD

**Issue by zhiephie** [libscode/libscode.github.io#1]

**Comment by SunDi3yansyah** [comment]
Maybe, nanti ini akan dijadikan cloud demo
- Disini kita bisa memberikan demo berupa front page
- Asssets (JS, CSS, SCSS, SASS etc) baik dari project yang dikerjkan maupun assets dari libscode sendiri yang artinya hosting LibsCode hanya menampung file PHP saja.

Example:
- https://libscode.com/assets/bundle.min.css menjadi http://cloud.libscode.com/libscode/bundle.min.css (for LibsCode)
- http://cloud.libscode.com/project/errors/style.css digunakan untuk semua front 404, contohnya: http://bce918.projects.libscode.com/404

**Comment by dikiaap** [comment]
seperti cdn maybe :smile:

**Comment by zhiephie** [comment]
oke master" semua, makasih penjelasannya :+1:

**Comment by zhiephie** [comment]
Please add readme om @SunDi3yansyah  :v:

**Comment by dikiaap** [comment]
betul. ubah jg indexnya sprt deskripsi cloud demonya.

**Comment by SunDi3yansyah** [comment]
Minggu ini saya akan kerjakan bagaimana gambarannya :+1: semua assets libscode akan diarahkan ke cloud ini dan dari beberapa project yang sudah saya kerjakan.
Untuk project nanti bisa masuk ke folder `project` atau sub module

**Comment by zhiephie** [comment]
:+1:

**Comment by SunDi3yansyah** [comment]
@zhiephie Okay... goto tux
@dikiaap Okay

**Comment by dikiaap** [comment]
:+1: :+1: :+1:
