### ISSUE TITLE
Resolusi gambar yang terlalu HD libscode.com

### ISSUE THREAD

**Issue by dikiaap** [libscode/libscode.github.io#2]

**Comment by SunDi3yansyah** [comment]
Iya saya setuju, saya masih kurang paham gimana caranya? bisa diperkecil? apakah mengurangi kwalitas gambar atau tidak? jika itu yang terbaik lakukan saja :+1:

**Comment by dikiaap** [comment]
Kalo di web sama aja om. Kalo di zoom sedikit blur.

**Comment by SunDi3yansyah** [comment]
Kemudian apakah ingin diperkecil lagi ukuran dan size nya silakan berpendapat :smile:
